[package]
name = "deepsort-rs"
version = "0.1.0"
authors = ["Mike Seddon <seddonm1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
ndarray = { version = "0.15.3", features = ["blas"] }
ndarray-linalg = { features = ["intel-mkl-static"], git = "https://github.com/rust-ndarray/ndarray-linalg", branch = "master" }
pathfinding = "2.1.5"

[dev-dependencies]
rand = "0.8.4"
rand_distr = "0.4.1"
rand_pcg = "0.3.1"
criterion = "0.3"

[[bench]]
name = "tracker"
harness = false

[profile.bench]
debug = true