[package]
name = "deepsort-rs"
version = "0.1.0"
authors = ["Mike Seddon <seddonm1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"
ndarray-linalg = { features = ["intel-mkl-static"], git = "https://github.com/rust-ndarray/ndarray-linalg", branch = "master" }

[dev-dependencies]
itertools = "0.10.1"